local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Open Telescope file finding" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Open Telescope buffer finding" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = "Open Telescope grep" })
vim.keymap.set('n', '<leader>fm', builtin.keymaps, { desc = "Open Telescope keymap finding" })
